
module.exports = {

  get: jest.fn((url) => {
  if (url === 'api1.json') {
        return Promise.resolve({
            data: {"slug":"NCSU_vs_UNC_football_part4_1978","id":"http://localhost:3333/api/av/NCSU_vs_UNC_football_part4_1978","embedurl":"http://localhost:3333/embed/NCSU_vs_UNC_football_part4_1978","poster":{"id":"http://localhost:3333/processedav/NCSU_vs_UNC_football_part4_1978/NCSU_vs_UNC_football_part4_1978.png","format":"image/png","width":640,"height":480,"label":"Poster image"},"avmaterial":[{"id":"http://localhost:3333/processedav/NCSU_vs_UNC_football_part4_1978/NCSU_vs_UNC_football_part4_1978.webm","format":"video/webm","height":480,"width":640},{"id":"http://localhost:3333/processedav/NCSU_vs_UNC_football_part4_1978/NCSU_vs_UNC_football_part4_1978.mp4","format":"video/mp4","height":480,"width":640}],"captions":null,"type":"https://schema.org/VideoObject","sprites":{"id":"http://localhost:3333/processedav/NCSU_vs_UNC_football_part4_1978/NCSU_vs_UNC_football_part4_1978-sprite.vtt","format":"text/vtt","kind":"metadata","label":"image sprite metadata"},"transcript":null,"issilent":false,"duration":null}
        });
  }
  if (url === 'api2.json') {
        return Promise.resolve({
            data: {"slug":"mc00196-matsumoto-george-01-early-life","id":"http://localhost:3333/api/av/mc00196-matsumoto-george-01-early-life","embedurl":"http://localhost:3333/embed/mc00196-matsumoto-george-01-early-life","poster":{"id":"https://brand.ncsu.edu/img/downloads/hunt-interior-thumb.jpg","format":"image/png","width":750,"height":422,"label":"Poster image"},"avmaterial":[{"id":"http://localhost:3333/processedav/mc00196-matsumoto-george-01-early-life/mc00196-matsumoto-george-01-early-life.mp3","format":"audio/mp3"},{"id":"http://localhost:3333/processedav/mc00196-matsumoto-george-01-early-life/mc00196-matsumoto-george-01-early-life.ogg","format":"audio/ogg"}],"captions":{"id":"http://localhost:3333/processedav/mc00196-matsumoto-george-01-early-life/mc00196-matsumoto-george-01-early-life.vtt","format":"text/vtt","label":"Captions"},"type":"https://schema.org/audioObject","sprites":null,"transcript":[{"id":"http://localhost:3333/transcript/mc00196-matsumoto-george-01-early-life","format":"text/txt","label":"Text transcript"}, {"id":"https://d.lib.ncsu.edu/pdfs/mc00196-matsumoto-george-01-early-life.pdf","format":"application/pdf","label":"PDF transcript"}],"issilent":false,"duration":null}
        });
  }
  if (url == 'http://localhost:3333/processedav/mc00196-matsumoto-george-01-early-life/mc00196-matsumoto-george-01-early-life.vtt'){
    return Promise.resolve({
      data: 'WEBVTT\n\nNOTE This file was automatically generated by https://github.com/jronallo/video_sprites\n\n00:00:00.000 --> 00:00:05.000\nCaption \n00:00:05.001 --> 00:00:10.000\nCaption number 160,0,160,88\n\n00:00:10.001 --> 00:00:15.000\nCaption number 320,0,160,88\n\n00:00:15.001 --> 00:00:20.000\nCaption number 480,0,160,88\n\n00:00:20.001 --> 00:00:25.000\nCaption number 0,88,160,88\n\n00:00:25.001 --> 00:00:30.000\nCaption number 160,88,160,88\n\n00:00:30.001 --> 00:00:35.000\nCaption number 320,88,160,88\n\n00:00:35.001 --> 00:00:40.000\nCaption number 480,88,160,88\n\n00:00:40.001 --> 00:00:45.000\nCaption number 0,176,160,88\n\n00:00:45.001 --> 00:00:50.000\nCaption number 160,176,160,88\n\n00:00:50.001 --> 00:00:55.000\nCaption number 320,176,160,88\n\n00:00:55.001 --> 00:01:00.000\nCaption number 480,176,160,88\n\n00:01:00.001 --> 00:01:05.000\nCaption number 0,264,160,88\n\n00:01:05.001 --> 00:01:10.000\nCaption number 160,264,160,88\n\n00:01:10.001 --> 00:01:15.000\nCaption number 320,264,160,88\n\n00:01:15.001 --> 00:01:20.000\nCaption number 480,264,160,88\n'
    })
  }
})
}
