defaults: &defaults
  avoutputpath: /vagrant/public/processedav
  log_directory: /vagrant/log
  per_page: "100"
  inputpath: /vagrant
  audiofiletypes: 'wav,mp3,wma,aif,au,aiff,aifc,vorbis,cda,caf,voc,mid,midi,mpa,ogg,wpl,m4a'
  avtypes: 'wav,mp3,wma,aif,au,aiff,aifc,vorbis,cda,caf,voc,mid,midi,mpa,ogg,wpl,m4a,3g2,3gp,avi,flv,h264,m4v,mkv,mov,webm,mp4,mpg,mpeg,rm,swf,vob,wmv'
  ignorepath: /vagrant/public/
  default_poster: "https://cdn.pixabay.com/photo/2017/07/09/20/48/speaker-2488096_1280.png"
  host_url: 'localhost:3333'
  derivativewidth: '640'
  #APP_API_KEY: 'APP_API_KEY'
  #deepspeechmodels: '/vagrant/deepspeech'

development:
  <<: *defaults
  
test:
  <<: *defaults
  deepspeechmodels: 
  ignorepath: '/vagrant/test/fixtures/files/output/'
